shops_names = {
    [1] ={"Tienda de comida",299},
    [2] ={"Tienda de electronica",206},
    [3] ={"Tienda 24/7",210},
    [4] ={"Bar",55},
    [5] ={"Ferreteria",121},
    [6] ={"Prendas superiores Casual", 210},
    [7] ={"Prendas superiores Luxe", 210},
    [8] ={"Prendas inferiores Casual", 210},
    [9] ={"Prendas inferiores Luxe", 210},
    [10] ={"Zapatos casuales", 210},
    [11] ={"Zapatos lujosos", 210},
    [12] ={"Armas ilegales", 112},
    [13]={"Tienda de skins", 217},
    [14]={"Tienda de ropa", 210},

}
 
shops = {
    [1] = {--TIENDA DE COMIDA
        {id=1, slot=5, title="Patatas normales" ,desc="Cantidad de usos: 5", price=5},
        {id=2, slot=5, title="Pizza mediana", desc="Cantidad de usos: 5", price=8},
        {id=3, slot=2, title="Ensalada", desc="Cantidad de usos: 2", price=10},
        {id=9, slot=5, title="Hotdog grande", desc="Cantidad de usos: 5", price=15},
        {id=10, slot=10, title="Paquete de helados", desc="Cantidad de usos: 10", price=15},
        {id=4, slot=2, title="Botella pequeña", desc="Cantidad de usos: 2", price=2},
        {id=4, slot=5, title="Botella grande", desc="Cantidad de usos: 5", price=4},
    },
    [2] = {--TIENDA DE ELECTRONICA
        {id=16, slot=1, title="iPhone",desc="Celular de ultima generacion.", price=50},
        {id=27, slot=1, title="Pendrive" ,desc="Guarda toda la musica y fotos que quieras.", price=50},
        {id=26, slot=1, title="CD" ,desc="CD para grabar toda la musica que quieras.", price=10},
        {id=28, slot=1, title="Radio para coche" ,desc="Radio para que escuches la mejor musica en tu coche", price=175},
        {id=25, slot=1, title="Reloj" ,desc="Podrás ver la hora con el.", price=45},
        {id=24, slot=1, title="GPS" ,desc="Sistema de Posicionamiento Global", price=210},
        {id=23, slot=1, title="Walkie-Talkie" ,desc="Ajusta la frecuencia para hablar con otras personas.", price=90},
        {id=29, slot=1, title="Cámara de fotos" ,desc="Camara de fotos HD", price=150},
    },
    [3] = {--TIENDA 24/7
        {id=4, slot=2, title="Botella pequeña", desc="Cantidad de usos: 2", price=2},
        {id=4, slot=5, title="Botella grande", desc="Cantidad de usos: 5", price=4},
        {id=1, slot=4, title="Patatas fritas" ,desc="Cantidad de usos: 4", price=8},
        {id=33, slot=2, title="Macarrones instantáneos" ,desc="Cantidad de usos: 2", price=15},
        {id=32, slot=2, title="Sopa instantánea" ,desc="Cantidad de usos: 2", price=16},
        {id=41, slot=10, title="Galletas" ,desc="Cantidad de usos: 10", price=10},
        {id=42, slot=3, title="Chocolate" ,desc="Cantidad de usos: 3", price=5},
        {id=49, slot=1, title="Mechero" ,desc="Sirve para encender cigarros", price=6},
    },
   
    [4] = {--BAR
        {id=51, slot=6, title="Cigarros" ,desc="Cantidad de usos: 6", price=45},
        {id=6, slot=3, title="Cerveza" ,desc="Cantidad de usos: 3", price=12},
        {id=5, slot=3, title="Vino" ,desc="Cantidad de usos: 3", price=16},
        {id=7, slot=4, title="Whisky" ,desc="Cantidad de usos: 4", price=20},
        {id=11, slot=5, title="Vodka" ,desc="Cantidad de usos: 5", price=28},
        {id=1, slot=6, title="Patatas fritas" ,desc="Cantidad de usos: 6", price=10},
 
    },
    [5] = {--FERRETERIA
        {id=48, slot=1, title="Duplicado de llaves" ,desc="Con esta herramienta podrás duplicar las llaves de tu casa o coche", price=80},
        {id=47, slot=1, title="Alarma para el coche" ,desc="Alarma para tu coche", price=120},
    },
    [6] = {--PRENDAS SUPERIORES CASUALES
        {1, 'Chaqueta marrón abierta', 'Una chaqueta de cuero marrón abierta con una camiseta blanca', 50},
        {4, 'Buzo abierto negro', 'Una chaqueta negra abierta con una camiseta blanca', 40},
        {5, 'Remera azul "Nada puede malir sal"', 'Camiseta azul con estampa "Nada puede malir sal"', 25},
        {6, 'Remera Radiohead', 'Camiseta blanca con logo de Radiohead', 25},
        {7, 'Remera de Eazy-E', 'Camiseta del rapero Eazy-E', 25},
        {8, 'Remera Converse negra', 'Camiseta negra de la marca Converse', 25},
        {11, 'Chaqueta negra con detalles blancos', 'Una chaqueta oscura con algunos detalles blancos', 35},
        {14, 'Chaqueta roja abierta con remera blanca', 'Una chaqueta roja con una camiseta blanca', 35},
        {15, 'Remera blanca y verde', 'Camiseta de color blanco y verde', 20},
        {16, 'Remera de bolos negra', 'Una camisa oscura perfecta para jugar a los bolos', 30},
        {17, 'Camisa verde mangas largas cerrada', 'Una camisa cerrada verde con mangas largas', 35},
        {18, 'Camisa negra mangas largas cerrada', 'Una camisa cerrada negra con mangas largas', 35},
        {19, 'Chaqueta verde abierta con remera blanca', 'Chaqueta abierta color verde con una camiseta blanca debajo', 30},
        {21, 'Camisa hawaiana azul y blanca', 'Presume de tu camisa hawaiana azul y blanca', 30},
        {22, 'Camisa hawaiana blanca', 'Presume de tu camisa hawaiana blanca', 30},
        {23, 'Buzo verde "Base 5"', 'Sudadera verde de Base 5', 35},
        {24, 'Buzo negro con capucha', 'Una sudadera negra con capucha', 35},
        {25, 'Buzo azul con capucha', 'Una sudadera azul con capucha', 35},
        {28, 'Camisa celeste mangas cortas con remera blanca mangas largas', 'Una camisa celeste con una camiseta blanca por debajo', 30},
        {29, 'Camisa negra mangas cortas con remera blanca mangas largas', 'Una camisa negra con una camiseta blanca por debajo', 30},
        {30, 'Camisa amarilla mangas cortas ccon remera blanca mangas largas', 'Una camisa amarilla con una camiseta blanca por debajo', 30},
        {31, 'Camisa azul casi prendida', 'Una camisa azul oscuro', 35},
        {32, 'Remera azul deportiva', 'Una camiseta azul de mangas cortas de estilo deportivo', 20},
        {33, 'Buzo gris', 'Sudadera gris con logo de Rockstar', 35},
        {34, 'Camisa negra con detalles rojos', 'Una camisa de color negro con algunos detalles en rojo', 25},
        {35, 'Remera con rayas blancas y azules', 'Una camiseta con rayas blancas y azules a juego', 20},
        {36, 'Remera blanca "Base 5"', 'Una camiseta grisácea de la marca Base 5', 25},
        {37, 'Remera blanca "Homies"', 'Una camiseta blanca con el logo de Homies', 25},
        {38, 'Remera de mono blanca con detalles rojos', 'Una camiseta con el logotipo de un mono', 25},
        {39, 'Remera verde', 'Una camiseta simple de color verde', 20},
        {40, 'Remera gris con logo de un arma', 'Una camiseta simple de color gris con una Uzi', 25},
        {41, 'Remera verde con logo de un arma', 'Una camiseta simple de color verde con una Uzi', 25},
        {42, 'Remera gris "Mercury"', 'Camiseta gris de la marca Mercury', 25},
        {45, 'Remera roja "Prolaps"', 'Camiseta roja de la marca Prolaps', 25},
        {46, 'Chaqueta de jean sin mangas con remera blanca', 'Un chaleco con una camiseta blanca por debajo', 30},
        {47, 'Remera blanca con logo "Suburban"', 'Camiseta de la marca Suburban', 25},
        {48, 'Remera beige "Zip"', 'Camiseta beige de la marca Zip', 25},
        {49, 'Remera gris "Zip"', 'Camiseta gris de la marca Zip', 25},
        {51, 'Buzo verde "Rockstar"', 'Una sudadera verde con el logo de Rockstar', 35},
        {52, 'Buzo gris marca "Mercury"', 'Una sudadera gris de la marca Mercury', 35},
        {53, 'Buzo gris claro "Rockstar"', 'Una sudadera gris claro de Rockstar', 35},
        {54, 'Buzo gris oscuro "Rockstar"', 'Una sudadera gris oscuro de Rockstar', 35},
        {55, 'Chupa de cuero', 'Cazadora negra de cuero con una cobra a sus espaldas', 75},
        {56, 'Chaqueta azul cuello amplio marca "R"', 'Una chaqueta azul cerrada de la marca R', 50},
        {57, 'Camisa azul cerrada', 'Una camisa azul oscuro cerrada y con bolsillos', 60},
        {58, 'Camisa azul con rayas blancas', 'Una elegante camisa azul con rayas blancas que la hacen de cuadros', 40},
        {59, 'Camisa verde con remera blanca', 'Camisa verde semiabierta con una camiseta blanca', 30},
        {60, 'Remera marrón mangas largas', 'Camiseta pegada marrón de mangas largas', 30},
        {61, 'Campera beige "Dude"', 'Una chaqueta color beige de la marca "Dude"', 35},
        {68, 'Remera mangas blancas larga con detalles rojos', 'Una chaqueta deportiva roja y blanca de Prolaps', 55},
        {103, 'Remera negra de Marilyn Monroe', 'Una camiseta negra con Marilyn Monroe en ella', 80},
        {104, 'Remera negra Armani AX', 'Camiseta negra de Armani', 90},
        {105, 'Remera blanca ARX', 'Una camiseta blanca ARX', 85},
        {106, 'Remera azul Brooklyn', 'Camiseta azul oscuro de Brooklyn', 90},   
        {107, 'Remera negra 86', 'Una camiseta negra con el número 86', 75},
        {108, 'Remera negra Jericho', 'Una camiseta negra "AEW is Jericho"', 85},
        {109, 'Remera negra Calvin Klein', 'Camiseta negra de la marca Calvin Klein', 95},
        {110, 'Remera Converse azul', 'Camiseta azul de la marca Converse', 80},
        {111, 'Remera negra Outta Straight', 'Camiseta negra "Straight Outta Los Santos"', 85},
        {112, 'Remera negra y blanca "Los Santos"', 'Camiseta negra y blanca de "Los Santos"', 80},
        {113, 'Remera blanca Wasted', 'Camiseta blanca "Wasted"', 75},
        {114, 'Remera blanca Supreme', 'Camiseta blanca de la marca Supreme', 70},
        {115, 'Chaqueta de jean azul', 'Una bonita y elegante chaqueta vaquera azul', 85},
    },

    [7] = {--prendas de lujo superiores
        {10, 'Traje gris oscuro con corbata blanca', 'Chaqueta de traje gris oscuro con una corbata blanca', 100},
        {62, 'Traje negro con remera blanca lisa', 'Chaqueta negra de traje con camiseta blanca', 75},
        {63, 'Traje celeste', 'Chaqueta azul celeste de traje con camiseta blanca', 75},
        {64, 'Traje verde', 'Chaqueta verde de traje con camiseta negra', 75},
        {65, 'Traje blanco', 'Chaqueta blanca de traje con camiseta negra', 75},
        {66, 'Traje rojo', 'Chaqueta roja de traje con camiseta blanca', 75},
        {67, 'Esmoquin negro a rayas con corbata', 'Una elegante chaqueta de esmoquin a rayas para combinar', 100},
        {69, 'Traje negro con pañuelo blanco y camisa blanca', 'Una elegante chaqueta negra de traje con un pañuelo blanco y camiseta del mismo color', 120},
        {70, 'Garzón negro con camisa blanca', 'Un elegante chaleco rojo con camisa blanca y pajarita negra', 150},
        {71, 'Garzón rojo con camisa blanca', 'Un elegante chaleco rojo con camisa blanca y pajarita negra', 150},

    },
    [8] ={--prendas inferiores casual
        {2, 'Jeans azules claros', 'Pantalones vaqueros de un azul claro', 70},
        {12, 'Pantalón marrón', 'Pantalones vaqueros de color marrón', 60},
        {13, 'Jeans azules oscuros', 'Pantalones vaqueros de un azul oscuro', 70},
        {20, 'Chinos blancos', 'Unos pantalones chinos de color blanco', 40},
        {26, 'Chinos negros', 'Unos pantalones chinos de color negro', 40},
        {27, 'Chinos azules', 'Unos pantalones chinos de color azul', 40},
        {50, 'Chinos beige', 'Unos pantalones chinos de color beige', 40},
        {72, 'Chinos oliva', 'Unos pantalones chinos de color oliva', 40},
        {76, 'Pantalón deportivo gris', 'Pantalones de deporte grises', 40},
        {77, 'Pantalón deportivo azul con rayas laterales blancas', 'Pantalones de deporte azules con rayas blancas', 40},
        {78, 'Pantalón deportivo gris con rayas laterales blancas', 'Pantalones de deporte grises con rayas blancas', 40},
        {79, 'Pantalón deportivo azul con rayas laterales rojas', 'Pantalones de deporte azules con rayas rojas', 40},
        {80, 'Pantalón verde camuflado', 'Pantalones verdes oscuros de camuflaje', 55},
        {81, 'Pantalón gris camuflado', 'Pantalones grises claros de camuflaje', 55},
        {82, 'Pantalón gris', 'Unos pantalones grises básicos', 45},
        {83, 'Pantalón verde', 'Unos pantalones verdes básicos', 45},
        {84, 'Pantalón de cuero', 'Unos pantalones de cuero oscuro, perfectos para montar en moto', 65},
    },

    [9] = {--prendas inferiores luxe
        {73, 'Pantalón de vestir negro', 'Pantalones de vestir de color negro', 45},
        {74, 'Pantalón de vestir gris con rayas', 'Pantalones de vestir grises con rayas', 50},
        {75, 'Pantalón de vestir gris', 'Pantalones de vestir grises', 45},
        {75, 'Pantalón de vestir gris', 'Pantalones de vestir grises', 45},
        {75, 'Pantalón de vestir gris', 'Pantalones de vestir grises', 45},
    },

    [10] = {--zapatos casuales
        {3, 'Borcegos marrones', 'Unos zapatos marrones al estilo de botas pequeñas', 35},
        {85, 'Botas negras', 'Unas botas negras de cuero al estilo de un motero', 60},
        {86, 'Converse negras', 'Botas de la marca Converse color negro', 45},
        {87, 'Lanvs negras', 'Botas de la marca Lanvs color negro', 40},
        {88, 'Converse marrones', 'Botas de la marca Converse color marrón', 45},
        {89, 'Converse rojas', 'Botas de la marca Converse color rojo', 45},
        {90, 'Zapatillas "Prolaps" azules', 'Unas botas de Prolaps de color azul', 45},
        {91, 'Botas de cowboy negras', 'Botas negras para parecer un auténtico cowboy', 60},
        {92, 'Botas de cowboy marrones', 'Botas marrones para parecer un auténtico cowboy', 60},
        {93, 'Sandalias con calcetines', 'Unas sandalias simples acompañadas por unos calcetines', 30},
        {94, 'Zapatillas deportivas blancas', 'Unas zapatillas de deporte blancas con tonos azulados', 50},
        {98, 'Zapatillas Adidas negras', 'Unas zapatillas de la marca Adidas de color negro', 50},
        {99, 'Zapatillas "Sneaker" negras/gris', 'Unas zapatillas de la marca Sneaker de color negro y gris', 45},
        {100, 'Zapatillas Vans negras', 'Unas zapatillas de la marca Vans de color negro', 45},
        {101, 'Zapatillas deportivas negras', 'Unas zapatillas negras muy cómodas', 40},
        {102, 'Zapatillas de montaña marrones', 'Unas zapatillas marrones de montaña perfectas para escalar', 40},
    },

    [11] = {--zapatos lujo
        {95, 'Zapatos negros', 'Unos elegantes zapatos negros para combinar con un traje', 85},
        {96, 'Zapatos marrones', 'Unos elegantes zapatos marrones para combinar con un traje', 85},
        {97, 'Zapatos negros lustrados', 'Unos elegantes zapatos negros y blancos para combinar con un traje', 85},
        {97, 'Zapatos negros lustrados', 'Unos elegantes zapatos negros y blancos para combinar con un traje', 85},
        {97, 'Zapatos negros lustrados', 'Unos elegantes zapatos negros y blancos para combinar con un traje', 85},
    },


    [12] = {--TIENDA DE ARMAS ILEGALES
        {id=14, slot=100, title="Colt45" ,desc="Munición: 100 balas", price=2500},
        {id=84, slot=1, title="Bate de beisbol", desc="Un bate de beisbol de madera", price=500},
        -- {id=86, slot=1, title="Cuchillo de combate", desc="Cuchillo ilegal afilado", price=1000},
        {id=92, slot=100, title="Colt45 con silenciador", desc="Munición: 100", price=3500},
        {id=97, slot=500, title="Uzi", desc="Munición: 250", price=4320},
        {id=99, slot=500, title="Tec-9", desc="Munición: 250", price=5310},
        {id=100, slot=200, title="AK-47", desc="Munición: 200", price=7500},
    },

    [13] = {
        --{id=9, slot=1, title='Business Lady',desc='', price=500}
    }, -- Tienda de Skin Femeninas
    [14] = {--prendas de lujo superiores
        {127, 'Buzo gucci', 'Un buzo gucci militar', 100},
        {128, 'Camiseta de lakers', 'Una camiseta con el estampado de lakers', 100},

    },

}

for i,v in ipairs({9, 10, 11, 12, 13, 31, 38, 39, 40, 41, 53, 54, 55, 56, 63, 64, 69, 91, 93, 129, 130, 131, 138, 139, 140, 141, 145, 148, 150, 151, 152, 157, 169, 172, 178, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 201, 205, 207, 214, 215, 216, 218, 219, 224, 225, 226, 231, 232, 233, 237, 238, 243, 244, 245, 246, 251, 256, 257, 263, 298, 304}) do
    table.insert(shops[13], {id=v, slot=1, title=getSkinNameFromID(v),desc='', price=500})
end
