local listaitems = {
    [1] = {name="Patatas fritas",isStackeable=true, itype="comida", value=0},
    [2] = {name="Pizza",isStackeable=true, itype="comida", value=0},
    [3] = {name="Ensalada",isStackeable=true, itype="comida", value=0},
    [4] = {name="Agua",isStackeable=true, itype="bebida", value=0},
    [5] = {name="Vino",isStackeable=true, itype="bebida", value=0},
    [6] = {name="Cerveza",isStackeable=true, itype="bebida", value=0},
    [7] = {name="Whisky",isStackeable=true, itype="bebida", value=0},
    [8] = {name="Sprunk",isStackeable=true, itype="bebida", value=0},
    [9] = {name="Perrito caliente",isStackeable=true, itype="comida", value=0},
    [10] = {name="Helado",isStackeable=true, itype="comida", value=0},
    [11] = {name="Vodka",isStackeable=true, itype="bebida", value=0},
    [12] = {name="Llave de vehículo",isStackeable=false, itype="llave", value=0},
    [13] = {name="Llave de propiedad",isStackeable=false, itype="llave", value=0},
    [14] = {name="Colt 45",isStackeable=false, itype="arma", value=22},
    [15] = {name="Granada de mano",isStackeable=false, itype="arma", value=16},
    [16] = {name="iPhone",isStackeable=false, itype="telefono", value=0},
    [17] = {name="Samsung",isStackeable=false, itype="telefono", value=0},
    [18] = {name="Tarjeta de crédito",isStackeable=false, itype="tarjeta", value=0},
    [19] = {name="Cheque bancario",isStackeable=false, itype="cheque", value=0},
    [20] =  {name="DNI",isStackeable=false, itype="documento", value=0},
    [21] =  {name="Licencia de Conducir",isStackeable=false, itype="documento", value=0},
    [22] =  {name="Licencia de Arma",isStackeable=false, itype="documento", value=0},
    [23] =  {name="WalkieTalkie",isStackeable=false, itype="misc", value=0},
    [24] =  {name="GPS",isStackeable=false, itype="misc", value=0},
    [25] =  {name="Reloj",isStackeable=false, itype="misc", value=0},
    [26] =  {name="CD",isStackeable=false, itype="misc", value=0},
    [27] =  {name="Pendrive",isStackeable=false, itype="misc", value=0},
    [28] =  {name="RadioCoche",isStackeable=false, itype="misc", value=0},
    [29] =  {name="Cámara de Fotos",isStackeable=false, itype="arma", value=43},
    [30] =  {name="Hamburguesa",isStackeable=false, itype="comida", value=0},
    [31] =  {name="Lata de sardinas",isStackeable=true, itype="comida", value=0},
    [32] =  {name="Sopa instantánea",isStackeable=false, itype="comida", value=0},
    [33] =  {name="Macarrones",isStackeable=false, itype="comida", value=0},
    [34] =  {name="Manzana",isStackeable=true, itype="comida", value=0},
    [35] =  {name="Banana",isStackeable=true, itype="comida", value=0},
    [36] =  {name="Naranja",isStackeable=true, itype="comida", value=0},
    [37] =  {name="Pera",isStackeable=true, itype="comida", value=0},
    [38] =  {name="Mango",isStackeable=true, itype="comida", value=0},
    [39] =  {name="Tomate",isStackeable=true, itype="comida", value=0},
    [40] =  {name="Lechuga",isStackeable=true, itype="comida", value=0},
    [41] =  {name="Galletas",isStackeable=true, itype="comida", value=0},
    [42] =  {name="Chocolate",isStackeable=true, itype="comida", value=0},
    [43] =  {name="Crack",isStackeable=true, itype="droga", value=0},
    [44] =  {name="Marihuana",isStackeable=true, itype="droga", value=0},
    [45] =  {name="Heroína",isStackeable=true, itype="droga", value=0},
    [46] =  {name="Cocaína",isStackeable=true, itype="droga", value=0},
    [47] =  {name="Alarma coche",isStackeable=false, itype="misc", value=0},
    [48] =  {name="Duplicar llaves",isStackeable=false, itype="misc", value=0},
    [49] =  {name="Mechero",isStackeable=false, itype="misc", value=0},
    [50] =  {name="Papel de liar",isStackeable=false, itype="misc", value=0},
    [51] =  {name="Tabaco",isStackeable=false, itype="misc", value=0},
    [52] =  {name="Ganzúas",isStackeable=false, itype="misc", value=0},
    [53] =  {name="Jeringas",isStackeable=false, itype="misc", value=0},
    [54] =  {name="Bong",isStackeable=false, itype="misc", value=0},
    [55] =  {name="Caja",isStackeable=false, itype="contenedor", value=0},
    [56] =  {name="Mochila pequeña",isStackeable=false, itype="contenedor", value=0},
    [57] =  {name="Mochila mediana",isStackeable=false, itype="contenedor", value=0},
    [58] =  {name="Mochila grande",isStackeable=false, itype="contenedor", value=0},
    [59] =  {name="Maleta",isStackeable=false, itype="contenedor", value=0},
    [60] =  {name="Maletin",isStackeable=false, itype="contenedor", value=0},
    [61] =  {name="Bolsa de deporte",isStackeable=false, itype="contenedor", value=0},
    [62] =  {name="Bolsa de la compra",isStackeable=false, itype="contenedor", value=0},
    [63] =  {name="Palanca",isStackeable=false, itype="mecanico", value=0},
    [64] =  {name="Juego de herramientas",isStackeable=false, itype="mecanico", value=0},
    [65] =  {name="Compresor",isStackeable=false, itype="mecanico", value=0},
    [66] =  {name="Bujía",isStackeable=false, itype="pieza", value=0},
    [67] =  {name="Neumático",isStackeable=false, itype="pieza", value=0},
    [68] =  {name="Correa de distribución",isStackeable=false, itype="pieza", value=0},
    [69] =  {name="Batería",isStackeable=false, itype="pieza", value=0},
    [70] =  {name="Carburador",isStackeable=false, itype="pieza", value=0},
    [71] = {name="Perrito caliente",isStackeable=true, itype="medicina", value=0},
    [72] =  {name="Vendaje",isStackeable=false, itype="medicina", value=0},
    [73] =  {name="Jeringas",isStackeable=false, itype="medicina", value=0},
    [74] =  {name="Agua oxigenada",isStackeable=false, itype="medicina", value=0},
    [75] =  {name="Morfina",isStackeable=false, itype="medicina", value=0},
    [76] =  {name="Desfibrilador",isStackeable=false, itype="medicina", value=0},
    [77] =  {name="Alcohol antiséptico",isStackeable=false, itype="medicina", value=0},
    [78] =  {name="Radio",isStackeable=false, itype="police", value=0},
    [79] =  {name="Esposas",isStackeable=false, itype="police", value=0},
    [80] =  {name="Medidor de alcoholemia",isStackeable=false, itype="police´", value=0},
    [81] =  {name="Taser",isStackeable=false, itype="arma", value="taser"},
    [82] =  {name="Manopla",isStackeable=false, itype="arma", value=1},
    [83] =  {name="Palo de golf",isStackeable=false, itype="arma", value=2},
    [84] =  {name="Bate de baseball",isStackeable=false, itype="arma", value=5},
    [85] =  {name="Porra de policía",isStackeable=false, itype="arma", value=3},
    [86] =  {name="Cuchillo",isStackeable=false, itype="arma", value=4},
    [87] =  {name="Katana",isStackeable=false, itype="arma", value=8},
    [88] =  {name="Pala",isStackeable=false, itype="arma", value=6},
    [89] =  {name="Taco de billar",isStackeable=false, itype="arma", value=7},
    [90] =  {name="Motosierra",isStackeable=false, itype="arma", value=9},
    [91] =  {name="Colt 45",isStackeable=false, itype="arma", value=22},
    [92] =  {name="Colt 45 Silenciada",isStackeable=false, itype="arma", value=23},
    [93] =  {name="Desert Eagle",isStackeable=false, itype="arma", value=24},
    [94] =  {name="Escopeta",isStackeable=false, itype="arma", value=25},
    [95] =  {name="Escopeta recortada",isStackeable=false, itype="arma", value=26},
    [96] =  {name="Escopeta de combate",isStackeable=false, itype="arma", value=27},
    [97] =  {name="Uzi",isStackeable=false, itype="arma", value=28},
    [98] =  {name="MP5",isStackeable=false, itype="arma", value=29},
    [99] =  {name="TEC-9",isStackeable=false, itype="arma", value=32},
    [100] =  {name="Kalashnikov",isStackeable=false, itype="arma", value=30},
    [101] =  {name="M4",isStackeable=false, itype="arma", value=31},
    [102] =  {name="Rifle de caza",isStackeable=false, itype="arma", value=33},
    [103] =  {name="Rifle de francotirador",isStackeable=false, itype="arma", value=34},
    [104] =  {name="RPG",isStackeable=false, itype="arma", value=35},
    [105] =  {name="Lanzador teledirigido",isStackeable=false, itype="arma", value=36},
    [106] =  {name="Lanzallamas",isStackeable=false, itype="arma", value=37},
    [107] =  {name="Minigun",isStackeable=false, itype="arma", value=38},
    [108] =  {name="Gas lacrimógeno",isStackeable=false, itype="arma", value=17},
    [109] =  {name="Molotov",isStackeable=false, itype="arma", value=18},
    [110] =  {name="Carga explosiva",isStackeable=false, itype="arma", value=39},
    [111] =  {name="Spray de pintura",isStackeable=false, itype="arma", value=41},
    [112] =  {name="Extintor",isStackeable=false, itype="arma", value=42},
    [113] =  {name="Dildo violeta",isStackeable=false, itype="arma", value=10},
    [114] =  {name="Dildo",isStackeable=false, itype="arma", value=11},
    [115] =  {name="Vibrador",isStackeable=false, itype="arma", value=12},
    [116] =  {name="Ramo de flores",isStackeable=false, itype="arma", value=14},
    [117] =  {name="Bastón",isStackeable=false, itype="arma", value=15},
    [118] =  {name="Vision nocturna",isStackeable=false, itype="arma", value=44},
    [119] =  {name="Infrarojos",isStackeable=false, itype="arma", value=45},
    [120] =  {name="Paracaidas",isStackeable=false, itype="arma", value=46},
    [121] =  {name="Detonador",isStackeable=false, itype="arma", value=40},
    [122] =  {name="Cargador de Pistola",isStackeable=false, itype="cargador", value=0},
    [123] =  {name="Cargador de Escopeta",isStackeable=false, itype="cargador", value=0},
    [124] =  {name="Cargador de Rifle",isStackeable=false, itype="cargador", value=0},
    [125] =  {name="Cargador de Sniper",isStackeable=false, itype="cargador", value=0}
   
   
}

function getItemNameFromID( id )
	return listaitems[ id ].name or false
end